import React, { useState } from 'react';
import { Settings, Sliders, ShieldCheck, Camera, Mic, Save, Check } from 'lucide-react';

const SettingsPage = () => {
  const [weights, setWeights] = useState({
    eyeContact: 15,
    posture: 12,
    speakingSpeed: 13,
    voice: 12,
    fillerWords: 10,
    pauses: 10,
    facialExpression: 10,
    headPosition: 10,
    handGestures: 10,
    bodyMovement: 8
  });

  const [saved, setSaved] = useState(false);

  const handleSliderChange = (key, value) => {
    setWeights(prev => ({ ...prev, [key]: Number(value) }));
    setSaved(false);
  };

  const handleSave = () => {
    setSaved(true);
    setTimeout(() => setSaved(false), 2500);
  };

  return (
    <div className="max-w-4xl mx-auto py-8 space-y-8">
      <div>
        <h1 className="text-2xl sm:text-3xl font-bold text-white tracking-tight flex items-center gap-2.5">
          <Settings className="w-7 h-7 text-indigo-400" /> Application & Coaching Settings
        </h1>
        <p className="text-xs sm:text-sm text-slate-400 mt-1">
          Customize your presentation scoring weight preferences and review system parameters.
        </p>
      </div>

      {/* Configurable Scoring Weights */}
      <div className="glass-panel p-6 sm:p-8 rounded-3xl space-y-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <Sliders className="w-5 h-5 text-indigo-400" />
            <h2 className="text-base font-bold text-white">Scoring Weight Distribution</h2>
          </div>
          <button
            onClick={handleSave}
            className="flex items-center gap-1.5 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-semibold shadow-glow transition-all"
          >
            {saved ? <Check className="w-4 h-4 text-emerald-400" /> : <Save className="w-4 h-4" />}
            <span>{saved ? 'Weights Saved' : 'Save Preferences'}</span>
          </button>
        </div>

        <p className="text-xs text-slate-400">
          Adjust the priority weights for different observable factors in overall presentation scoring.
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 pt-2">
          {Object.entries(weights).map(([key, val]) => (
            <div key={key} className="space-y-2 p-3.5 rounded-2xl bg-slate-900/60 border border-slate-800">
              <div className="flex items-center justify-between text-xs font-semibold">
                <span className="text-slate-200 capitalize">
                  {key.replace(/([A-Z])/g, ' $1')}
                </span>
                <span className="text-indigo-400 font-mono">{val}%</span>
              </div>
              <input
                type="range"
                min="5"
                max="30"
                value={val}
                onChange={(e) => handleSliderChange(key, e.target.value)}
                className="w-full accent-indigo-500 cursor-pointer"
              />
            </div>
          ))}
        </div>
      </div>

      {/* Privacy & Observability Disclaimer */}
      <div className="glass-panel-glow p-6 sm:p-8 rounded-3xl border-indigo-500/30">
        <div className="flex items-center gap-3 mb-3">
          <ShieldCheck className="w-6 h-6 text-emerald-400 shrink-0" />
          <h3 className="text-base font-bold text-white">Presentation Performance Disclaimer</h3>
        </div>
        <p className="text-xs text-slate-300 leading-relaxed">
          The score generated by ConfidenceAI represents <strong>observable behavioral delivery factors</strong> (such as eye contact ratio, speech cadence, posture alignment, and filler word frequency). It is intended exclusively for communication coaching and rehearsal improvement. It does not measure psychological confidence, medical traits, cognitive conditions, or internal anxiety.
        </p>
      </div>
    </div>
  );
};

export default SettingsPage;
